apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: newargonamespace-sept25-gitops
  description: This is GitOps manifest for newargonamespace-sept25   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: newargonamespace-sept25
    janus-idp.io/tekton: newargonamespace-sept25 
    backstage.io/kubernetes-id: newargonamespace-sept25 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:newargonamespace-sept25
