---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: newargonamespace-sept25
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: newargonamespace-sept25 
  name: newargonamespace-sept25
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi